#!/bin/bash
#dpkg -i: install
#echo "Pre-install: $1";

if [ $1 == "install" ]; then
	echo "1) Stopping XBMC";
	/etc/init.d/xbmc stop 1>/dev/null 2>/dev/null >/dev/null

	if [ -f /home/xbian/update.log ]; then
		rm /home/xbian/update.log;
	fi
	
	if [ ! -d /usr/local/lib/xbmc/addons/library.xbmc.addon ]; then
		mkdir -p /usr/local/lib/xbmc/addons/library.xbmc.addon;
	fi

	if [ ! -d /usr/local/lib/xbmc/addons/library.xbmc.gui ]; then
		mkdir -p /usr/local/lib/xbmc/addons/library.xbmc.gui;
	fi

	if [ ! -d /usr/local/lib/xbmc/addons/library.xbmc.pvr ]; then
		mkdir -p /usr/local/lib/xbmc/addons/library.xbmc.pvr;
	fi

	if [ ! -d /usr/local/lib/xbmc/addons/visualization.glspectrum ]; then
		mkdir -p /usr/local/lib/xbmc/addons/visualization.glspectrum;
	fi

	if [ ! -d /usr/local/lib/xbmc/addons/visualization.waveform ]; then
		mkdir -p /usr/local/lib/xbmc/addons/visualization.waveform;
	fi

	if [ ! -d /usr/local/lib/xbmc/system ]; then
		mkdir -p /usr/local/lib/xbmc/system;
	fi

	if [ ! -d /usr/local/lib/xbmc/system/players/dvdplayer ]; then
		mkdir -p /usr/local/lib/xbmc/system/players/dvdplayer;
	fi

	if [ ! -d /usr/local/lib/xbmc/system/players/paplayer ]; then
		mkdir -p /usr/local/lib/xbmc/system/players/paplayer;
	fi

	if [ ! -d /usr/local/lib/xbmc ]; then
		mkdir -p /usr/local/lib/xbmc;
	fi

	if [ ! -d /usr/local/sbin ]; then
		mkdir -p /usr/local/sbin;
	fi

	if [ ! -d /boot ]; then
		mkdir -p /boot;
	fi

	if [ ! -d /etc ]; then
		mkdir -p /etc;
	fi

	if [ ! -d /lib/modules/3.2.27/kernel/drivers/staging/media/lirc ]; then
		mkdir -p /lib/modules/3.2.27/kernel/drivers/staging/media/lirc;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/arch/arm/oprofile ]; then
		mkdir -p /lib/modules/3.6.1/kernel/arch/arm/oprofile;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/crypto ]; then
		mkdir -p /lib/modules/3.6.1/kernel/crypto;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/base/regmap ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/base/regmap;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/block ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/block;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/block/drbd ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/block/drbd;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/bluetooth ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/bluetooth;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/cdrom ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/cdrom;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/connector ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/connector;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/cpufreq ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/cpufreq;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/extcon ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/extcon;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/hid ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/hid;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/hsi/clients ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/hsi/clients;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/hsi ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/hsi;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/i2c/algos ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/i2c/algos;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/i2c/busses ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/i2c/busses;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/i2c ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/i2c;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/input ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/input;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/input/gameport ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/input/gameport;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/input/misc ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/input/misc;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/input/serio ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/input/serio;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/leds ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/leds;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/media/common/tuners ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/media/common/tuners;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/media/dvb/b2c2 ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/media/dvb/b2c2;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/media/dvb/dvb-core ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/media/dvb/dvb-core;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/media/dvb/dvb-usb ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/media/dvb/dvb-usb;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/media/dvb/frontends ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/media/dvb/frontends;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/media/dvb/siano ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/media/dvb/siano;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/media/radio ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/media/radio;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/media/radio/si470x ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/media/radio/si470x;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/media/rc ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/media/rc;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/media/rc/keymaps ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/media/rc/keymaps;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/media/video ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/media/video;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/media/video/cx231xx ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/media/video/cx231xx;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/media/video/cx25840 ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/media/video/cx25840;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/media/video/em28xx ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/media/video/em28xx;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/media/video/gspca/gl860 ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/media/video/gspca/gl860;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/media/video/gspca ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/media/video/gspca;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/media/video/gspca/m5602 ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/media/video/gspca/m5602;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/media/video/gspca/stv06xx ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/media/video/gspca/stv06xx;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/media/video/hdpvr ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/media/video/hdpvr;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/media/video/pvrusb2 ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/media/video/pvrusb2;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/media/video/pwc ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/media/video/pwc;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/media/video/sn9c102 ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/media/video/sn9c102;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/media/video/tlg2300 ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/media/video/tlg2300;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/media/video/usbvision ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/media/video/usbvision;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/media/video/uvc ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/media/video/uvc;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/misc ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/misc;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/misc/eeprom ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/misc/eeprom;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/net/bonding ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/net/bonding;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/net/hamradio ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/net/hamradio;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/net/irda ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/net/irda;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/net ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/net;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/net/phy ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/net/phy;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/net/ppp ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/net/ppp;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/net/slip ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/net/slip;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/net/usb ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/net/usb;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/net/wimax/i2400m ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/net/wimax/i2400m;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/net/wireless ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/net/wireless;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/net/wireless/ath ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/net/wireless/ath;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/net/wireless/ath/ath9k ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/net/wireless/ath/ath9k;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/net/wireless/ath/carl9170 ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/net/wireless/ath/carl9170;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/net/wireless/b43 ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/net/wireless/b43;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/net/wireless/b43legacy ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/net/wireless/b43legacy;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/net/wireless/hostap ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/net/wireless/hostap;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/net/wireless/libertas ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/net/wireless/libertas;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/net/wireless/libertas_tf ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/net/wireless/libertas_tf;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/net/wireless/mwifiex ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/net/wireless/mwifiex;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/net/wireless/p54 ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/net/wireless/p54;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/net/wireless/rt2x00 ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/net/wireless/rt2x00;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/net/wireless/rtl818x/rtl8187 ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/net/wireless/rtl818x/rtl8187;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/net/wireless/rtl8192cu ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/net/wireless/rtl8192cu;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/net/wireless/zd1211rw ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/net/wireless/zd1211rw;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/nfc ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/nfc;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/rtc ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/rtc;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/scsi ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/scsi;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/spi ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/spi;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/ssb ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/ssb;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/staging/csr ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/staging/csr;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/staging/gdm72xx ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/staging/gdm72xx;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/staging/media/lirc ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/staging/media/lirc;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/staging/ozwpan ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/staging/ozwpan;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/staging/rtl8712 ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/staging/rtl8712;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/staging/winbond ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/staging/winbond;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/staging/wlan-ng ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/staging/wlan-ng;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/staging/zram ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/staging/zram;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/uio ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/uio;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/usb/chipidea ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/usb/chipidea;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/usb/class ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/usb/class;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/usb/host ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/usb/host;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/usb/image ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/usb/image;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/usb/misc ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/usb/misc;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/usb/mon ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/usb/mon;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/usb/phy ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/usb/phy;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/usb/serial ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/usb/serial;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/usb/storage ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/usb/storage;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/video/backlight ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/video/backlight;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/video ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/video;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/w1/masters ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/w1/masters;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/w1/slaves ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/w1/slaves;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/w1 ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/w1;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/drivers/watchdog ]; then
		mkdir -p /lib/modules/3.6.1/kernel/drivers/watchdog;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/fs/9p ]; then
		mkdir -p /lib/modules/3.6.1/kernel/fs/9p;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/fs ]; then
		mkdir -p /lib/modules/3.6.1/kernel/fs;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/fs/btrfs ]; then
		mkdir -p /lib/modules/3.6.1/kernel/fs/btrfs;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/fs/cifs ]; then
		mkdir -p /lib/modules/3.6.1/kernel/fs/cifs;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/fs/ecryptfs ]; then
		mkdir -p /lib/modules/3.6.1/kernel/fs/ecryptfs;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/fs/fuse ]; then
		mkdir -p /lib/modules/3.6.1/kernel/fs/fuse;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/fs/gfs2 ]; then
		mkdir -p /lib/modules/3.6.1/kernel/fs/gfs2;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/fs/hfs ]; then
		mkdir -p /lib/modules/3.6.1/kernel/fs/hfs;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/fs/hfsplus ]; then
		mkdir -p /lib/modules/3.6.1/kernel/fs/hfsplus;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/fs/isofs ]; then
		mkdir -p /lib/modules/3.6.1/kernel/fs/isofs;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/fs/jfs ]; then
		mkdir -p /lib/modules/3.6.1/kernel/fs/jfs;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/fs/nfsd ]; then
		mkdir -p /lib/modules/3.6.1/kernel/fs/nfsd;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/fs/nilfs2 ]; then
		mkdir -p /lib/modules/3.6.1/kernel/fs/nilfs2;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/fs/nls ]; then
		mkdir -p /lib/modules/3.6.1/kernel/fs/nls;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/fs/ntfs ]; then
		mkdir -p /lib/modules/3.6.1/kernel/fs/ntfs;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/fs/ocfs2/cluster ]; then
		mkdir -p /lib/modules/3.6.1/kernel/fs/ocfs2/cluster;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/fs/ocfs2/dlm ]; then
		mkdir -p /lib/modules/3.6.1/kernel/fs/ocfs2/dlm;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/fs/ocfs2/dlmfs ]; then
		mkdir -p /lib/modules/3.6.1/kernel/fs/ocfs2/dlmfs;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/fs/ocfs2 ]; then
		mkdir -p /lib/modules/3.6.1/kernel/fs/ocfs2;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/fs/quota ]; then
		mkdir -p /lib/modules/3.6.1/kernel/fs/quota;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/fs/reiserfs ]; then
		mkdir -p /lib/modules/3.6.1/kernel/fs/reiserfs;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/fs/squashfs ]; then
		mkdir -p /lib/modules/3.6.1/kernel/fs/squashfs;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/fs/udf ]; then
		mkdir -p /lib/modules/3.6.1/kernel/fs/udf;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/fs/xfs ]; then
		mkdir -p /lib/modules/3.6.1/kernel/fs/xfs;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/lib ]; then
		mkdir -p /lib/modules/3.6.1/kernel/lib;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/lib/xz ]; then
		mkdir -p /lib/modules/3.6.1/kernel/lib/xz;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/lib/zlib_deflate ]; then
		mkdir -p /lib/modules/3.6.1/kernel/lib/zlib_deflate;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/lib/zlib_inflate ]; then
		mkdir -p /lib/modules/3.6.1/kernel/lib/zlib_inflate;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/net/802 ]; then
		mkdir -p /lib/modules/3.6.1/kernel/net/802;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/net/8021q ]; then
		mkdir -p /lib/modules/3.6.1/kernel/net/8021q;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/net/9p ]; then
		mkdir -p /lib/modules/3.6.1/kernel/net/9p;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/net/ax25 ]; then
		mkdir -p /lib/modules/3.6.1/kernel/net/ax25;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/net/bluetooth ]; then
		mkdir -p /lib/modules/3.6.1/kernel/net/bluetooth;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/net/bluetooth/bnep ]; then
		mkdir -p /lib/modules/3.6.1/kernel/net/bluetooth/bnep;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/net/bluetooth/hidp ]; then
		mkdir -p /lib/modules/3.6.1/kernel/net/bluetooth/hidp;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/net/bluetooth/rfcomm ]; then
		mkdir -p /lib/modules/3.6.1/kernel/net/bluetooth/rfcomm;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/net/bridge ]; then
		mkdir -p /lib/modules/3.6.1/kernel/net/bridge;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/net/bridge/netfilter ]; then
		mkdir -p /lib/modules/3.6.1/kernel/net/bridge/netfilter;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/net/core ]; then
		mkdir -p /lib/modules/3.6.1/kernel/net/core;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/net/ipv4 ]; then
		mkdir -p /lib/modules/3.6.1/kernel/net/ipv4;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/net/ipv4/netfilter ]; then
		mkdir -p /lib/modules/3.6.1/kernel/net/ipv4/netfilter;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/net/ipv6 ]; then
		mkdir -p /lib/modules/3.6.1/kernel/net/ipv6;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/net/ipv6/netfilter ]; then
		mkdir -p /lib/modules/3.6.1/kernel/net/ipv6/netfilter;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/net/irda/ircomm ]; then
		mkdir -p /lib/modules/3.6.1/kernel/net/irda/ircomm;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/net/irda ]; then
		mkdir -p /lib/modules/3.6.1/kernel/net/irda;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/net/irda/irlan ]; then
		mkdir -p /lib/modules/3.6.1/kernel/net/irda/irlan;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/net/irda/irnet ]; then
		mkdir -p /lib/modules/3.6.1/kernel/net/irda/irnet;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/net/key ]; then
		mkdir -p /lib/modules/3.6.1/kernel/net/key;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/net/l2tp ]; then
		mkdir -p /lib/modules/3.6.1/kernel/net/l2tp;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/net/llc ]; then
		mkdir -p /lib/modules/3.6.1/kernel/net/llc;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/net/mac80211 ]; then
		mkdir -p /lib/modules/3.6.1/kernel/net/mac80211;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/net/netfilter/ipset ]; then
		mkdir -p /lib/modules/3.6.1/kernel/net/netfilter/ipset;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/net/netfilter ]; then
		mkdir -p /lib/modules/3.6.1/kernel/net/netfilter;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/net/netrom ]; then
		mkdir -p /lib/modules/3.6.1/kernel/net/netrom;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/net/nfc ]; then
		mkdir -p /lib/modules/3.6.1/kernel/net/nfc;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/net/openvswitch ]; then
		mkdir -p /lib/modules/3.6.1/kernel/net/openvswitch;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/net/rose ]; then
		mkdir -p /lib/modules/3.6.1/kernel/net/rose;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/net/sched ]; then
		mkdir -p /lib/modules/3.6.1/kernel/net/sched;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/net/wimax ]; then
		mkdir -p /lib/modules/3.6.1/kernel/net/wimax;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/net/wireless ]; then
		mkdir -p /lib/modules/3.6.1/kernel/net/wireless;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/net/xfrm ]; then
		mkdir -p /lib/modules/3.6.1/kernel/net/xfrm;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/sound/arm ]; then
		mkdir -p /lib/modules/3.6.1/kernel/sound/arm;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/sound/core/oss ]; then
		mkdir -p /lib/modules/3.6.1/kernel/sound/core/oss;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/sound/core/seq/oss ]; then
		mkdir -p /lib/modules/3.6.1/kernel/sound/core/seq/oss;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/sound/core/seq ]; then
		mkdir -p /lib/modules/3.6.1/kernel/sound/core/seq;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/sound/core ]; then
		mkdir -p /lib/modules/3.6.1/kernel/sound/core;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/sound/drivers/mpu401 ]; then
		mkdir -p /lib/modules/3.6.1/kernel/sound/drivers/mpu401;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/sound/drivers ]; then
		mkdir -p /lib/modules/3.6.1/kernel/sound/drivers;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/sound ]; then
		mkdir -p /lib/modules/3.6.1/kernel/sound;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/sound/usb/6fire ]; then
		mkdir -p /lib/modules/3.6.1/kernel/sound/usb/6fire;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/sound/usb/caiaq ]; then
		mkdir -p /lib/modules/3.6.1/kernel/sound/usb/caiaq;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/sound/usb/misc ]; then
		mkdir -p /lib/modules/3.6.1/kernel/sound/usb/misc;
	fi

	if [ ! -d /lib/modules/3.6.1/kernel/sound/usb ]; then
		mkdir -p /lib/modules/3.6.1/kernel/sound/usb;
	fi

	if [ ! -d /lib/modules/3.6.1 ]; then
		mkdir -p /lib/modules/3.6.1;
	fi

	if [ ! -d /usr/local/include/xbian-config ]; then
		mkdir -p /usr/local/include/xbian-config;
	fi

	if [ ! -d /usr/local/include/xbian-config/scripts ]; then
		mkdir -p /usr/local/include/xbian-config/scripts;
	fi

	if [ ! -d /usr/local/share/doc/xbmc ]; then
		mkdir -p /usr/local/share/doc/xbmc;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.demo ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.demo;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.demo/addon ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.demo/addon;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.dvbviewer ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.dvbviewer;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.dvbviewer/addon ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.dvbviewer/addon;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.dvbviewer/addon/resources/language/English ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.dvbviewer/addon/resources/language/English;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.dvbviewer/addon/resources ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.dvbviewer/addon/resources;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.dvbviewer/resources/language/English ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.dvbviewer/resources/language/English;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.dvbviewer/resources ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.dvbviewer/resources;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.fortherecord.argus ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.fortherecord.argus;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.fortherecord.argus/addon ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.fortherecord.argus/addon;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.fortherecord.argus/addon/resources/language/Dutch ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.fortherecord.argus/addon/resources/language/Dutch;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.fortherecord.argus/addon/resources/language/English ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.fortherecord.argus/addon/resources/language/English;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.fortherecord.argus/addon/resources/language/Italian ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.fortherecord.argus/addon/resources/language/Italian;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.fortherecord.argus/addon/resources ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.fortherecord.argus/addon/resources;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.fortherecord.argus/resources/language/Dutch ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.fortherecord.argus/resources/language/Dutch;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.fortherecord.argus/resources/language/English ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.fortherecord.argus/resources/language/English;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.fortherecord.argus/resources/language/Italian ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.fortherecord.argus/resources/language/Italian;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.fortherecord.argus/resources ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.fortherecord.argus/resources;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.hts ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.hts;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.hts/addon ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.hts/addon;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.hts/addon/resources/language/Dutch ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.hts/addon/resources/language/Dutch;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.hts/addon/resources/language/English ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.hts/addon/resources/language/English;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.hts/addon/resources/language/Finnish ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.hts/addon/resources/language/Finnish;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.hts/addon/resources/language/German ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.hts/addon/resources/language/German;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.hts/addon/resources ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.hts/addon/resources;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.hts/resources/language/Dutch ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.hts/resources/language/Dutch;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.hts/resources/language/English ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.hts/resources/language/English;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.hts/resources/language/Finnish ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.hts/resources/language/Finnish;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.hts/resources/language/German ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.hts/resources/language/German;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.hts/resources ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.hts/resources;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.mediaportal.tvserver ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.mediaportal.tvserver;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.mediaportal.tvserver/TVServerXBMC ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.mediaportal.tvserver/TVServerXBMC;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.mediaportal.tvserver/addon ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.mediaportal.tvserver/addon;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.mediaportal.tvserver/addon/TVServerXBMC ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.mediaportal.tvserver/addon/TVServerXBMC;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.mediaportal.tvserver/addon/resources ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.mediaportal.tvserver/addon/resources;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.mediaportal.tvserver/addon/resources/language/Dutch ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.mediaportal.tvserver/addon/resources/language/Dutch;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.mediaportal.tvserver/addon/resources/language/English ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.mediaportal.tvserver/addon/resources/language/English;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.mediaportal.tvserver/addon/resources/language/Finnish ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.mediaportal.tvserver/addon/resources/language/Finnish;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.mediaportal.tvserver/addon/resources/language/German ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.mediaportal.tvserver/addon/resources/language/German;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.mediaportal.tvserver/addon/resources/language/Hebrew ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.mediaportal.tvserver/addon/resources/language/Hebrew;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.mediaportal.tvserver/addon/resources/language/Hungarian ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.mediaportal.tvserver/addon/resources/language/Hungarian;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.mediaportal.tvserver/addon/resources/language/Italian ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.mediaportal.tvserver/addon/resources/language/Italian;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.mediaportal.tvserver/addon/resources/language/Korean ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.mediaportal.tvserver/addon/resources/language/Korean;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.mediaportal.tvserver/resources ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.mediaportal.tvserver/resources;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.mediaportal.tvserver/resources/language/Dutch ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.mediaportal.tvserver/resources/language/Dutch;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.mediaportal.tvserver/resources/language/English ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.mediaportal.tvserver/resources/language/English;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.mediaportal.tvserver/resources/language/Finnish ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.mediaportal.tvserver/resources/language/Finnish;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.mediaportal.tvserver/resources/language/German ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.mediaportal.tvserver/resources/language/German;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.mediaportal.tvserver/resources/language/Hebrew ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.mediaportal.tvserver/resources/language/Hebrew;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.mediaportal.tvserver/resources/language/Hungarian ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.mediaportal.tvserver/resources/language/Hungarian;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.mediaportal.tvserver/resources/language/Italian ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.mediaportal.tvserver/resources/language/Italian;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.mediaportal.tvserver/resources/language/Korean ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.mediaportal.tvserver/resources/language/Korean;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.nextpvr ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.nextpvr;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.nextpvr/addon ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.nextpvr/addon;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.nextpvr/addon/resources/language/English ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.nextpvr/addon/resources/language/English;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.nextpvr/addon/resources ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.nextpvr/addon/resources;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.nextpvr/resources/language/English ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.nextpvr/resources/language/English;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.nextpvr/resources ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.nextpvr/resources;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.njoy ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.njoy;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.njoy/addon ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.njoy/addon;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.njoy/addon/resources/language/English ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.njoy/addon/resources/language/English;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.njoy/addon/resources ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.njoy/addon/resources;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.njoy/resources/language/English ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.njoy/resources/language/English;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.njoy/resources ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.njoy/resources;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.vdr.vnsi ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.vdr.vnsi;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.vdr.vnsi/addon ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.vdr.vnsi/addon;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.vdr.vnsi/addon/resources/language/Dutch ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.vdr.vnsi/addon/resources/language/Dutch;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.vdr.vnsi/addon/resources/language/English ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.vdr.vnsi/addon/resources/language/English;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.vdr.vnsi/addon/resources/language/Finnish ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.vdr.vnsi/addon/resources/language/Finnish;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.vdr.vnsi/addon/resources/language/German ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.vdr.vnsi/addon/resources/language/German;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.vdr.vnsi/addon/resources ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.vdr.vnsi/addon/resources;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.vdr.vnsi/addon/resources/skins/Confluence/720p ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.vdr.vnsi/addon/resources/skins/Confluence/720p;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.vdr.vnsi/resources/language/Dutch ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.vdr.vnsi/resources/language/Dutch;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.vdr.vnsi/resources/language/English ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.vdr.vnsi/resources/language/English;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.vdr.vnsi/resources/language/Finnish ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.vdr.vnsi/resources/language/Finnish;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.vdr.vnsi/resources/language/German ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.vdr.vnsi/resources/language/German;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.vdr.vnsi/resources ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.vdr.vnsi/resources;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.vdr.vnsi/resources/skins/Confluence/720p ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.vdr.vnsi/resources/skins/Confluence/720p;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.vdr.xvdr ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.vdr.xvdr;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.vdr.xvdr/resources/language/Dutch ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.vdr.xvdr/resources/language/Dutch;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.vdr.xvdr/resources/language/English ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.vdr.xvdr/resources/language/English;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.vdr.xvdr/resources/language/Finnish ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.vdr.xvdr/resources/language/Finnish;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.vdr.xvdr/resources/language/German ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.vdr.xvdr/resources/language/German;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.vdr.xvdr/resources ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.vdr.xvdr/resources;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.vdr.xvdr/resources/skins/Confluence/720p ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.vdr.xvdr/resources/skins/Confluence/720p;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.vuplus ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.vuplus;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.vuplus/addon ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.vuplus/addon;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.vuplus/addon/resources/language/English ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.vuplus/addon/resources/language/English;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.vuplus/addon/resources/language/German ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.vuplus/addon/resources/language/German;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.vuplus/addon/resources ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.vuplus/addon/resources;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.vuplus/resources/language/English ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.vuplus/resources/language/English;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.vuplus/resources/language/German ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.vuplus/resources/language/German;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/pvr.vuplus/resources ]; then
		mkdir -p /usr/local/share/xbmc/addons/pvr.vuplus/resources;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/screensaver.xbmc.builtin.dim/resources/language/Afrikaans ]; then
		mkdir -p /usr/local/share/xbmc/addons/screensaver.xbmc.builtin.dim/resources/language/Afrikaans;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/screensaver.xbmc.builtin.dim/resources/language/Arabic ]; then
		mkdir -p /usr/local/share/xbmc/addons/screensaver.xbmc.builtin.dim/resources/language/Arabic;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/screensaver.xbmc.builtin.slideshow/resources/language/Arabic ]; then
		mkdir -p /usr/local/share/xbmc/addons/screensaver.xbmc.builtin.slideshow/resources/language/Arabic;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/skin.confluence/language/Albanian ]; then
		mkdir -p /usr/local/share/xbmc/addons/skin.confluence/language/Albanian;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/visualization.dxspectrum/resources/language/Arabic ]; then
		mkdir -p /usr/local/share/xbmc/addons/visualization.dxspectrum/resources/language/Arabic;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/visualization.glspectrum/resources/language/Arabic ]; then
		mkdir -p /usr/local/share/xbmc/addons/visualization.glspectrum/resources/language/Arabic;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/visualization.milkdrop/resources/language/Afrikaans ]; then
		mkdir -p /usr/local/share/xbmc/addons/visualization.milkdrop/resources/language/Afrikaans;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/visualization.milkdrop/resources/language/Arabic ]; then
		mkdir -p /usr/local/share/xbmc/addons/visualization.milkdrop/resources/language/Arabic;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/visualization.projectm/resources/language/Arabic ]; then
		mkdir -p /usr/local/share/xbmc/addons/visualization.projectm/resources/language/Arabic;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/weather.wunderground/resources/language/Afrikaans ]; then
		mkdir -p /usr/local/share/xbmc/addons/weather.wunderground/resources/language/Afrikaans;
	fi

	if [ ! -d /usr/local/share/xbmc/addons/weather.wunderground/resources/language/Arabic ]; then
		mkdir -p /usr/local/share/xbmc/addons/weather.wunderground/resources/language/Arabic;
	fi

	if [ ! -d /var/lib/polkit-1/localauthority/50-local.d ]; then
		mkdir -p /var/lib/polkit-1/localauthority/50-local.d;
	fi
	
	echo "2) Installing new files"
fi